### ISSUE TITLE
An error randomly occurs when processing AvaTax queue

### ISSUE THREAD

**Issue by rsisco** [classyllama/ClassyLlama_AvaTax#94]
It has been reported that sometimes, when generating an invoice in the Magento backend, the following error is logged:

> PHP Fatal error: Uncaught Error: Call to a member function getId() on null in /vendor/classyllama/module-avatax/Helper/TaxClass.php:241
> 
> Stack trace:
> #0 /vendor/classyllama/module-avatax/Framework/Interaction/Tax.php(616): ClassyLlama\AvaTax\Helper\TaxClass->populateCorrectTaxClasses(Array, '1')
> #1 /vendor/classyllama/module-avatax/Framework/Interaction/Tax/Get.php(123): ClassyLlama\AvaTax\Framework\Interaction\Tax->getGetTaxRequestForSalesObject(Object(Magento\Sales\Model\Order\Invoice))
> #2 /vendor/classyllama/module-avatax/Model/Queue/Processing.php(350): ClassyLlama\AvaTax\Framework\Interaction\Tax\Get->processSalesObject(Object(Magento\Sales\Model\Order\Invoice))
> #3 /vendor/classyllama/module-avatax/Model/Queue/Processing.php(183): ClassyLlama\AvaTax\Model\Queue\Processing->processWithAvaTax(Object(ClassyLlama\AvaTax\Model\Queue), Object(Magento\Sales\Model\Order\Invoice))

### Steps to reproduce
1. Place an order
2. Generate invoice for the order
3. Process the AvaTax queue

### Expected result
1. The AvaTax queue is processed without error

### Actual result
1. The error indicated above is logged for some/all invoices in the queue

**Comment by rsisco** [comment]
This issue has been addressed in version [1.2.5](https://github.com/classyllama/ClassyLlama_AvaTax/releases/tag/1.2.5) by changing the way the product ID is retrieved.
